language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      # Get Python 3.7 from Xenial
      # https://github.com/travis-ci/travis-ci/issues/9815
      python: 3.7
      dist: xenial
    - os: windows
      # Get Python 3.7 from Chocolatey
      language: sh
      python: 3.7
      before_install:
        - choco install python --version 3.7
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - os: osx
      # Get Python 3.7 from pyenv
      language: sh
      python: 3.7
      before_install:
        - HOMEBREW_NO_INSTALL_CLEANUP=1 brew upgrade pyenv
        - git clone https://github.com/momo-lab/pyenv-install-latest.git "$(pyenv root)"/plugins/pyenv-install-latest
        - pyenv install-latest 3.7
        - pyenv global $(pyenv install-latest --print 3.7)
        - eval "$(pyenv init -)"


cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.pyenv/cache

install:
- python -m pip install --upgrade pip setuptools wheel
- python -m pip install . 'pytest>=4.0'

script:
- python -m pytest test_naucse_render
